delivery_app-master/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^cart$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<dish_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart/clear$', views.cart_clear, name='cart_clear'),
]

delivery_app-master/delivery_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'delivery_app'
urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'', include(('kitchen.urls', 'kitchen'), namespace='kitchen')),
    url(r'', include(('order.urls', 'order'), namespace='order')),
    url(r'', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'', include(('users.urls', 'users'), namespace='users')),
    # url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    # url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

delivery_app-master/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from users import views as user_views


app_name = 'users'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_views.profile, name='profile'),
]

delivery_app-master/users/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='media/default.jpg', upload_to='profile-pics')

    def __str__(self):
        return f'{self.user.username} Profile'

delivery_app-master/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    # Meta class gives information about the model and the fields shown in the form
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        help_texts = {
            'username': None,
            'email': None,
            'password1': None,
            'password2': None
        }


class UserUpdateForm(forms.Form):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

delivery_app-master/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from users.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Your account has been created! You can now log in')
            return redirect('users:login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/signup.html', {'form': form})


@login_required
def profile(request):
    u_form = UserUpdateForm()
    p_form = ProfileUpdateForm()
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request, 'users/profile.html')

delivery_app-master/users/templates/users/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'users/main.css' %}" type="text/css">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand  mr-4" href="/" id="logo-color">Delivery_app</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'kitchen:kitchen-list'%}">Browse</a>
                {% endif %}
              <a class="nav-item nav-link" href="#">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'users:profile' %}">Profile</a>
                    <a class="nav-item nav-link" href="{% url 'kitchen:kitchen-create'%}">Register Kitchen</a>
                    <a class="nav-item nav-link" href="{% url 'dish:dish-list'%}">My Kitchen</a>
                    <a class="nav-item nav-link" href="{% url 'users:logout' %}">Logout</a>
                {% else %}
                    <a class="nav-item nav-link" href="{% url 'users:register' %}">Register</a>
                    <a class="nav-item nav-link" href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{message.tags}}">
                        {{message}}
                    </div>
                {% endfor %}
            {% endif%}
          {% block content %}{% endblock %}
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</body>
</html>

delivery_app-master/users/templates/users/login.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>FreedomFeastor</title>
    <meta name="viewport" contenidth=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet"  href="{% static 'css/login.css' %}">

    <style>
        .body{ background-image: url( "{% static 'img/yum.jpg' %}");}
</style>
</head>
<body class="body">
<div class="login-page">
   <div class="login-page">
  <div class="form">

    <form method="POST">
            {% csrf_token %}
                {{ form.as_p}}
        <button type="submit" on click="window.location.href='login.html'" >SIGN IN</button>

    </form>
      <a href="{% url 'home' %}">Cancel</a>
  </div>
</div>
</div>
<script src="./assets/javascript/home.js"></script>
</body>
</html>

delivery_app-master/users/templates/users/logout.html
{% extends "users/base.html"%}
{% block content %}

<h5>You have been logged from your portal</h5>
<div class="border-top pt-3">
    <small class="muted">
        <a href="{% url 'users:login' %}" class="ml-2">
            Log In Again ?
        </a>
    </small>
</div>
{% endblock content %}

delivery_app-master/users/templates/users/profile.html
{% extends "users/base.html" %}
{% block content %}

<div class="content-section">

  <div class="media">
    <img class="rounded-circle account-img" src="/media/default.jpg">

    <div class="media-body">
      <h2 class="account-heading"> Welcome to your profile  {{user.username}}</h2>
      <p class="text-secondary">{{user.email}}</p>
    </div>
  </div>
  <!-- FORM HERE -->
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profile Info</legend>
                {{ u_form.as_p}}
                {{ p_form.as_p}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit"> Update</button>
            </div>
        </form>
</div>

{% endblock content %}

delivery_app-master/users/templates/users/register.html
{% extends "users/base.html" %}
{% block content %}

    <div class="content-section">
        <!-- REGISTRATION FORM WITH POST METHOD USING FORM FROM VIEWS CONTEXT -->
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                {{ form.as_p}}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Sign Up</button>
            </div>
        </form>

        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

delivery_app-master/users/templates/users/signup.html
{% load static %}
<!Doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>FreedomFeastor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


    <style>
        .body{ background-image: url( "{% static 'img/un.jpg' %}");}
    </style>
</head>

<body class="body">

<div class="login-page">
  <div class="form">

    <form method="POST">
            {% csrf_token %}
                {{ form.as_p}}
        <button type="submit" on click="window.location.href='login.html'" >SIGN UP</button>

    </form>
      <a href="{% url 'home' %}">Cancel</a>
  </div>
</div>

<script>
// Get the modal
var modal = document.getElementById('login-page');
// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
  if (event.target == modal) {
    modal.style.display = "none";
  }
}
</script>


</body>
</html>