delivery_app-master/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^cart$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<dish_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart/clear$', views.cart_clear, name='cart_clear'),
]

delivery_app-master/delivery_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'delivery_app'
urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'', include(('kitchen.urls', 'kitchen'), namespace='kitchen')),
    url(r'', include(('order.urls', 'order'), namespace='order')),
    url(r'', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'', include(('users.urls', 'users'), namespace='users')),
    # url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    # url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

delivery_app-master/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from users import views as user_views


app_name = 'users'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_views.profile, name='profile'),
]

delivery_app-master/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>{% block title %}Feast Freedom{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

       <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if user.is_authenticated%}

              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
             <li class="nav-item">
              <a class="nav-link" href="kitchens/new">Add Kitchen</a>
             </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
              </li>
            {% endif %}
           </li>
            <a class="nav-link" href="menu.html">Menu</a>
          </li>
        </ul>
      </div>
    </nav>
    <div id="subheader">
        <div class="cart">
            {% with total_items=cart|length %}
                {% if cart|length > 0 %}
                    Your cart:
                    <a href="{% url "cart:cart_detail" %}">
                        {{ total_items }} item{{ total_items|pluralize }}, ${{ cart.get_total_price }}
                    </a>
                {% else %}
                    Your cart is empty.
                {% endif %}
            {% endwith %}
        </div>
    </div>
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

delivery_app-master/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Freedom Feastor</title>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta name="description" content="Feastor Freedom">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="./assets/css/home.css">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-/uQFqO50IaQu2rNJYKPpV7zwsWJtd6V4DGX4wMw1ATz4KPuZEV96qQ2heVAw2kr2" crossorigin="anonymous">


  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

       <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if user.is_authenticated%}

              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
             <li class="nav-item">
              <a class="nav-link" href="kitchens/new">Add Kitchen</a>
             </li>

            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/login">Login</a>
              </li>
            {% endif %}
           </li>
            <a class="nav-link" href="menu.html">Menu</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="jumbotron text-center">
         <h1 class="display-3">Feastor Freedom!</h1>
         <p class="lead">A platform where you can order fresh homemade food</p>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

         <ol class="carousel-indicators">
           <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
           <li data-target="#myCarousel" data-slide-to="1"></li>
           <li data-target="#myCarousel" data-slide-to="2"></li>
         </ol>

        <div class="carousel-inner">
          <div class="item active">
            <img class="mySlides" src="static/img/plate.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/bk.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/food.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/straw.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/pret.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/scampi.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/mac.jpg" style="width:100%;">
          </div>

          <div class="item">
            <img class="mySlides" src="static/img/blue.jpg" style="width:100%;">
          </div>

        </div>

        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
           <span class="glyphicon glyphicon-chevron-left"></span>
           <span class="sr-only">Previous</span>
        </a>

        <a class="righ carousel-control" href=#myCarousel data-slide="next">
           <span class="glyphicon glyphicon-chevron-right"></span>
           <span class="sr-only">Next</span>
        </a>



    </div>
    </div>
    <script>
    var myIndex = 0;
    carousel();
    function carousel() {
      var i;
      var x = document.getElementsByClassName("mySlides");
      for (i = 0; i < x.length; i++) {
         x[i].style.display = "none";
      }
    myIndex++;
    if (myIndex > x.length) {myIndex = 1}
    x[myIndex-1].style.display = "block";
    setTimeout(carousel, 3000);
}
</script>

</body>
</html>


 </body>
</html>

delivery_app-master/templates/test.html
{% extends "base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>hello</h1>
    <p>This is a test homepage</p>

    <a href="/kitchens">kitchen</a>
    {% if user.is_authenticated %}
    <a href="/logout">logout</a>
    {% else %}
    <a href="/login">login</a>
    <a href="/register">register</a>
    {% endif %}
{% endblock %}