delivery_app-master/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^cart$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<dish_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart/clear$', views.cart_clear, name='cart_clear'),
]

delivery_app-master/delivery_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'delivery_app'
urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'', include(('kitchen.urls', 'kitchen'), namespace='kitchen')),
    url(r'', include(('order.urls', 'order'), namespace='order')),
    url(r'', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'', include(('users.urls', 'users'), namespace='users')),
    # url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    # url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

delivery_app-master/kitchen/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'kitchen'
urlpatterns = [
    url(r'^kitchens$', views.kitchen_list, name='kitchen_list'),
    url(r'^kitchens/(?P<pk>\d+)$', views.kitchen_details, name='kitchen_details'),
    url(r'^kitchens/(?P<pk>\d+)/update$', views.kitchen_update, name='kitchen_update'),
    url(r'^kitchens/new/$', views.kitchen_new, name='kitchen_new'),
    url(r'^kitchens/(?P<pk>\d+)/dishes$', views.dish_list, name='dish_list'),
    url(r'^kitchens/(?P<pkk>\d+)/dishes/(?P<pk>\d+)$', views.dish_details, name='dish_details'),
    url(r'^kitchens/(?P<pkk>\d+)/dishes/(?P<pk>\d+)/update$', views.dish_update, name='dish_update'),
    url(r'^kitchens/(?P<pk>\d+)/dishes/new$', views.dish_new, name='dish_new'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

delivery_app-master/users/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.contrib.auth import views as auth_views
from users import views as user_views


app_name = 'users'
urlpatterns = [
    path('signup/', views.register, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', user_views.profile, name='profile'),
]

delivery_app-master/kitchen/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


# Create your models here.
class Days(models.Model):
    Monday = models.BooleanField()
    Tuesday = models.BooleanField()
    Wednesday = models.BooleanField()
    Thursday = models.BooleanField()
    Friday = models.BooleanField()
    Saturday = models.BooleanField()
    Sunday = models.BooleanField()



class Kitchen(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50, unique=True)
    # password = models.CharField(max_length=100)
    # day = models.CharField(max_length=8, choices=DAYS_OF_WEEK)
    days = models.ForeignKey(Days, related_name='days', on_delete=models.CASCADE)
    start_time = models.TimeField()
    end_time = models.TimeField()
    image = models.ImageField(upload_to="kitchen/", blank=True, null=True)
    user = models.ForeignKey(User, related_name='kitchen_user', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('kitchen:kitchen_detail', kwargs={'pk': self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=50)
    veg = models.BooleanField()
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to="dish/", blank=True, null=True)
    kitchen = models.ForeignKey(Kitchen, null=True, related_name='dishes', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('kitchen:dish_detail', kwargs={'pkk': self.kitchen.pk, 'pk': self.pk})

delivery_app-master/kitchen/forms.py
from django.forms import ModelForm
from django import forms
from . models import Kitchen, Dish, Days


# DAYS_OF_WEEK = (
#     ('0', 'Monday'),
#     ('1', 'Tuesday'),
#     ('2', 'Wednesday'),
#     ('3', 'Thursday'),
#     ('4', 'Friday'),
#     ('5', 'Saturday'),
#     ('6', 'Sunday'),
# )


class KitchenForm(ModelForm):
    # widgets = {'day': forms.CheckboxSelectMultiple}
    # widgets = {'password': forms.PasswordInput}
    class Meta:
        model = Kitchen
        fields = ('name', 'email', 'start_time', 'end_time', 'image')


class DishForm(ModelForm):
    class Meta:
        model = Dish
        fields = ('name', 'veg', 'description', 'price', 'image')


class DaysForm(ModelForm):
    class Meta:
        model = Days
        fields = ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday')

delivery_app-master/kitchen/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import Kitchen, Dish, Days
from . forms import KitchenForm, DishForm, DaysForm
from cart.forms import CartAddForm
from django.contrib.auth.decorators import login_required


def kitchen_list(request):
    kitchens = Kitchen.objects.all()
    return render(request, 'kitchen/kitchen_list.html', {'kitchen_list':kitchens})


def kitchen_details(request,pk):
    kitchen = get_object_or_404(Kitchen,pk=pk)
    return render(request,'kitchen/kitchen_detail.html',{'kitchen':kitchen})


@login_required
def kitchen_new(request):
    if request.method == "POST":
        form = KitchenForm(request.POST, request.FILES)
        days_form = DaysForm(request.POST)
        if form.is_valid() and days_form.is_valid():
            work_days = days_form.save()
            kitchen = form.save(commit=False)
            kitchen.days = work_days
            kitchen.user = request.user
            kitchen.save()
            return redirect('kitchen:kitchen_details',pk=kitchen.pk)
    else:
        form = KitchenForm()
        days_form = DaysForm()
    return render(request,'kitchen/kitchen_edit.html',{'form':form, 'days_form':days_form})


def kitchen_update(request,pk):
    kitchen = Kitchen.objects.get(id=pk)
    days = Days.objects.get(id=kitchen.days.id)
    if request.method == "POST":
        form = KitchenForm(request.POST, request.FILES, instance=kitchen)
        days_form = DaysForm(request.POST, instance=days)
        if form.is_valid() and days_form.is_valid():
            work_days = days_form.save()
            kitchen = form.save(commit=False)
            kitchen.days = work_days
            kitchen.save()
            return redirect('kitchen:kitchen_details',pk=kitchen.pk)
    else:
        form = KitchenForm(instance=kitchen)
        days_form = DaysForm(instance=days)
    return render(request,'kitchen/kitchen_edit.html',{'form':form, 'days_form':days_form})


def dish_list(request, pk):
    dishes = Dish.objects.filter(kitchen = pk)
    return render(request, 'kitchen/dish_list.html', {'dish_list':dishes})


def dish_details(request,pkk,pk):
    dish = get_object_or_404(Dish,pk=pk)
    kitchen = get_object_or_404(Kitchen,pk=pkk)
    cart_add_form = CartAddForm()
    return render(request,'kitchen/dish_detail.html',{'dish':dish,
                                                      'kitchen':kitchen,
                                                      'cart_add_form': cart_add_form})


@login_required
def dish_new(request,pk):
    if request.method == "POST":
        form = DishForm(request.POST, request.FILES)
        if form.is_valid():
            dish = form.save(commit=False)
            dish.kitchen = Kitchen.objects.get(id=pk)
            dish.save()
            return redirect('kitchen:dish_details',pkk=dish.kitchen.pk,pk=dish.pk)
    else:
        form = DishForm()
    return render(request,'kitchen/dish_edit.html',{'form':form})


def dish_update(request, pkk, pk):
    dish = get_object_or_404(Dish, id=pk)
    if request.method == "POST":
        form = DishForm(request.POST, request.FILES, instance=dish)
        if form.is_valid():
            dish = form.save(commit=False)
            dish.kitchen = Kitchen.objects.get(id=pkk)
            dish.save()
            return redirect('kitchen:dish_details', pkk=pkk, pk=dish.pk)
    else:
        form = DishForm(instance=dish)
    return render(request, 'kitchen/dish_edit.html', {'form':form})

delivery_app-master/kitchen/templates/kitchen/dish_detail.html
{% extends "base.html" %}

{% block title %}
    Dish
{% endblock %}

{% block content %}

<h1>{{ dish.name }}</h1>
<p>Veg: {{ dish.veg }}</p>
<p>Description: {{ dish.description|linebreaksbr }}</p>
<p>Price: ${{ dish.price }}</p>
{% if dish.image %}
    <p><img src="{{ dish.image.url }}" style="width: 120px"/></p>
{% endif %}
<form action="{% url "cart:cart_add" dish.id %}" method="post">
    {{ cart_add_form }}
    {% csrf_token %}
    <input type="submit" value="Add to cart">
</form>
<p>Served by <a href="{% url 'kitchen:kitchen_details' kitchen.id %}">{{ kitchen.name }}</a></p>

{% if request.user == kitchen.user %}
    <a href="{% url 'kitchen:dish_update' kitchen.id dish.id %}">edit dish info</a>
{% endif %}
{% endblock %}

{% block footer %}

{% endblock %}

delivery_app-master/kitchen/templates/kitchen/dish_edit.html
{% extends "base.html" %}

{% block title %}
    Add New Dish
{% endblock %}

{% block content %}
  <form method='post' class="kitchen_form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class='save button'>save</button>
  </form>
{% endblock %}

delivery_app-master/kitchen/templates/kitchen/dish_list.html
<html>
<title>W3.CSS Template</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Sidebar (hidden by default) -->
<nav class="w3-sidebar w3-bar-block w3-card w3-top w3-xlarge w3-animate-left" style="display:none;z-index:2;width:40%;min-width:300px" id="mySidebar">
  <a href="javascript:void(0)" onclick="w3_close()"
  class="w3-bar-item w3-button">Close Menu</a>
  <a href="#food" onclick="w3_close()" class="w3-bar-item w3-button">Food</a>
  <a href="#about" onclick="w3_close()" class="w3-bar-item w3-button">About</a>
</nav>

<!-- Top menu -->
<div class="w3-top">
  <div class="w3-white w3-xlarge" style="max-width:1200px;margin:auto">
    <div class="w3-button w3-padding-16 w3-left" onclick="w3_open()">&#9776;</div>
    <div class="w3-right w3-padding-16">Mail</div>
    <div class="w3-center w3-padding-16">My Food</div>
  </div>
</div>

<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">

  <!-- First Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center" id="food">
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real NYC Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/steak.jpg" alt="Steak" style="width:100%">
      <h3>Let Me Tell You About This Steak</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/cherries.jpg" alt="Cherries" style="width:100%">
      <h3>Cherries, interrupted</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
      <p>What else?</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/wine.jpg" alt="Pasta and Wine" style="width:100%">
      <h3>Once Again, Robust Wine and Vegetable Pasta</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>

  <!-- Second Photo Grid-->
  <div class="w3-row-padding w3-padding-16 w3-center">
    <div class="w3-quarter">
      <img src="/w3images/popsicle.jpg" alt="Popsicle" style="width:100%">
      <h3>All I Need Is a Popsicle</h3>
      <p>Lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/salmon.jpg" alt="Salmon" style="width:100%">
      <h3>Salmon For Your Skin</h3>
      <p>Once again, some random text to lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/sandwich.jpg" alt="Sandwich" style="width:100%">
      <h3>The Perfect Sandwich, A Real Classic</h3>
      <p>Just some random text, lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
    <div class="w3-quarter">
      <img src="/w3images/croissant.jpg" alt="Croissant" style="width:100%">
      <h3>Le French</h3>
      <p>Lorem lorem lorem lorem ipsum text praesent tincidunt ipsum lipsum.</p>
    </div>
  </div>

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="#" class="w3-bar-item w3-button w3-hover-black">&laquo;</a>
      <a href="#" class="w3-bar-item w3-black w3-button">1</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">2</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">3</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">4</a>
      <a href="#" class="w3-bar-item w3-button w3-hover-black">&raquo;</a>
    </div>
  </div>

  <hr id="about">

  <!-- About Section -->
  <div class="w3-container w3-padding-32 w3-center">
    <h3>About Me, The Food Man</h3><br>
    <img src="/w3images/chef.jpg" alt="Me" class="w3-image" style="display:block;margin:auto" width="800" height="533">
    <div class="w3-padding-32">
      <h4><b>I am Who I Am!</b></h4>
      <h6><i>With Passion For Real, Good Food</i></h6>
      <p>Just me, myself and I, exploring the universe of unknownment. I have a heart of love and an interest of lorem ipsum and mauris neque quam blog. I want to share my world with you. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla. Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
    </div>
  </div>
  <hr>

  <!-- Footer -->
  <footer class="w3-row-padding w3-padding-32">
    <div class="w3-third">
      <h3>FOOTER</h3>
      <p>Praesent tincidunt sed tellus ut rutrum. Sed vitae justo condimentum, porta lectus vitae, ultricies congue gravida diam non fringilla.</p>
      <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>

    <div class="w3-third">
      <h3>BLOG POSTS</h3>
      <ul class="w3-ul w3-hoverable">
        <li class="w3-padding-16">
          <img src="/w3images/workshop.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Lorem</span><br>
          <span>Sed mattis nunc</span>
        </li>
        <li class="w3-padding-16">
          <img src="/w3images/gondol.jpg" class="w3-left w3-margin-right" style="width:50px">
          <span class="w3-large">Ipsum</span><br>
          <span>Praes tinci sed</span>
        </li>
      </ul>
    </div>

    <div class="w3-third w3-serif">
      <h3>POPULAR TAGS</h3>
      <p>
        <span class="w3-tag w3-black w3-margin-bottom">Travel</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">New York</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dinner</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Salmon</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">France</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Drinks</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Ideas</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Flavors</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Cuisine</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Chicken</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Dressing</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fried</span>
        <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Fish</span> <span class="w3-tag w3-dark-grey w3-small w3-margin-bottom">Duck</span>
      </p>
    </div>
  </footer>

<!-- End page content -->
</div>

<script>
// Script to open and close sidebar
function w3_open() {
  document.getElementById("mySidebar").style.display = "block";
}

function w3_close() {
  document.getElementById("mySidebar").style.display = "none";
}
</script>

</body>

delivery_app-master/kitchen/templates/kitchen/kitchen_detail.html
{% extends "base.html" %}

{% block title %}
    Kitchen
{% endblock %}

{% block content %}

<h2>
<a href="{% url 'kitchen:dish_list' kitchen.id %}">Menu</a>
</h2>


{% if request.user == kitchen.user %}
    <a href="{% url 'kitchen:kitchen_update' kitchen.id %}">edit kitchen info</a>
    <a href="{% url 'kitchen:dish_new' kitchen.id %}">add dishes</a>
{% endif %}

<h1>
    {{ kitchen.name }}

</h1>

<p>
{% if kitchen.days.Monday == 1 %}
Mon {% endif %}
{% if kitchen.days.Tuesday == 1 %}
Tue {% endif %}
{% if kitchen.days.Wednesday == 1 %}
Wed {% endif %}
{% if kitchen.days.Thursday == 1 %}
Thur {% endif %}
{% if kitchen.days.Friday == 1 %}
Fri {% endif %}
{% if kitchen.days.Saturday == 1 %}
Sat {% endif %}
{% if kitchen.days.Sunday == 1 %}
Sun {% endif %}
</p>
<p>{{ kitchen.start_time }}</p>
<p>{{ kitchen.end_time }}</p>
{% if kitchen.image %}
<p><img src="{{ kitchen.image.url }}" style="width: 120px"/></p>
{% endif %}

{% endblock %}
{% block footer %}

{% endblock %}

delivery_app-master/kitchen/templates/kitchen/kitchen_edit.html
{% extends "base.html" %}
{% block title %}
    Add New Kitchen
{% endblock %}
{% block content %}
  <form method='post' class="kitchen_form" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  Working Days:
  {{ days_form.as_p }}
  <button type="submit" class='save button'>save</button>
  </form>
{% endblock %}

delivery_app-master/kitchen/templates/kitchen/kitchen_list.html
{% load static %}
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>FreedomFeastor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="./assets/css/bk.css">
     <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="./assets/css/home.css">
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/pulse/bootstrap.min.css" rel="stylesheet" integrity="sha384-/uQFqO50IaQu2rNJYKPpV7zwsWJtd6V4DGX4wMw1ATz4KPuZEV96qQ2heVAw2kr2" crossorigin="anonymous">


</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

       <div class="collapse navbar-collapse" id="navbarColor01">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
            {% if user.is_authenticated%}

              <li class="nav-item">
                <a class="nav-link" href="/logout">Logout</a>
              </li>
            <li class="nav-item">
              <a class="nav-link" href="/kitchens/new">Add Kitchen</a>
             </li>


            {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'users:signup' %}">Sign Up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/login">Login</a>
          </li>
            {% endif %}
           </li>
            <a class="nav-link" href="menu.html">Menu</a>
          </li>
        </ul>
      </div>
    </nav>

    <div class="navbar">
      <a href="home.html">Home</a>
      <a href="menu.html">Menu</a>
      <a href="bk.html">Breakfast</a>
      <a href="lunch.html">Lunch</a>
      <a href="dinner.html">Dinner</a>
    </div>

    <div class="header" float:"middle";>
      <h1>Kitchen</h1>
      <h3></h3>
    {% for kitchen in kitchen_list %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ kitchen.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'user-posts' post.author.username %}">{{ kitchen.name }}</a>
            </div>
          </div>
        </article>
    {% endfor %}



</body>
</html>

delivery_app-master/kitchen/templates/kitchen/menu.html
<!doctype html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>FreedomFeastor</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Gothic&display=swap" rel="stylesheet" type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-beta/css/materialize.min.css">
    <link rel="stylesheet" href="./assets/css/bk.css">

</head>

<body>

    <div class="navbar">
      <a href="home.html">Home</a>
      <a href="menu.html">Menu</a>
      <a href="bk.html">Breakfast</a>
      <a href="lunch.html">Lunch</a>
      <a href="dinner.html">Dinner</a>
    </div>

    <div class="header" float:"middle";>
      <h1>Breakfast Choices:</h1>
      <h3></h3>



       <div class="image123">
        <div class="imgContainer">
          <img src="./assets/images/pan.jpg" height="600" width="500"/>
       </div>
       <div class="imgContainer">
         <img src="./assets/images/waf.jpg" height="600" width="400"/>
       </div>
       <div class="imgContainer">
         <img src="./assets/images/egg.jpg" height="600" width="400"/>
       </div>
       </div>
    </div>




</body>
</html>