delivery_app-master/cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^cart$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<dish_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url(r'^cart/clear$', views.cart_clear, name='cart_clear'),
]

delivery_app-master/delivery_app/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'delivery_app'
urlpatterns = [
    # path('admin/', admin.site.urls),
    url(r'^admin/', admin.site.urls),
    url(r'', include(('kitchen.urls', 'kitchen'), namespace='kitchen')),
    url(r'', include(('order.urls', 'order'), namespace='order')),
    url(r'', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'', include(('users.urls', 'users'), namespace='users')),
    # url(r'^accounts/login/$', LoginView.as_view(), name='login'),
    # url(r'^accounts/logout/$', LogoutView.as_view(), name='logout'),
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
]

delivery_app-master/order/urls.py
from django.conf.urls import url
from . import views

app_name = 'orders'
urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
    url(r'^order/$', views.order_list, name='order_list'),
    url(r'^order/(?P<order_id>\d+)$', views.order_detail, name='order_detail')
]

delivery_app-master/cart/models.py
from django.db import models

# Create your models here.

delivery_app-master/cart/forms.py
from django import forms


DISH_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=DISH_QUANTITY_CHOICES,
                                      coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

delivery_app-master/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from kitchen.models import Dish
from .cart import Cart
from .forms import CartAddForm
from django.contrib import messages


@require_POST
def cart_add(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    # for item in cart:
    #     kitchen = item['dish'].kitchen
    if cart.__len__() != 0 and dish.kitchen != cart.get_provider():
        messages.error(request, 'Cannot add dishes from different kitchen.')
    else:
        form = CartAddForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            cart.add(dish=dish,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, dish_id):
    cart = Cart(request)
    dish = get_object_or_404(Dish, id=dish_id)
    cart.remove(dish)
    messages.success(request, 'Remove dishes successfully.')
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddForm(initial={'quantity': item['quantity'],
                                                            'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

delivery_app-master/cart/templates/cart/detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Menu
{% endblock %}

{% block content %}
<div class="title">
    Shopping Bag
    <a href="/cart/clear" >Clear Shopping Cart</a>
    <a href="/kitchens/{{ cart.get_provider.id }}/dishes" >Continue Shopping</a>
  </div>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class="{{ message.tags }}"{% endif %}> {{ message }} </li>
    {% endfor %}
</ul>
{% endif %}
<div class="shopping-cart">

  {% for item in cart %}
  <div class="item">
    <div class="buttons">
      <span class="delete-btn"><a href="{% url "cart:cart_remove" item.dish.id %}" >X</a></span>
    </div>

    <div class="image">
      <img src="{% if item.dish.image %}{{ item.dish.image }}{% else %}{% static "img/no_image.png" %}{% endif %}">
    </div>

    <div class="description">
      {{item.dish.name}}
    </div>

      <div class="price">
          ${{item.price}}
      </div>

    <div class="quantity">
      <form action="{% url "cart:cart_add" item.dish.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Update">
                {% csrf_token %}
        </form>
    </div>

    <div class="total-price">${{item.total_price}}</div>
  </div>
     {% endfor %}
    <div class="total">
        <span>Total: ${{ cart.get_total_price|floatformat:"2" }}</span>
    </div>
    </div>

    <a href="{% url "orders:order_create" %}" class="button-checkout">Checkout</a>

{% endblock %}